image: debian:stable

stages:
  - analyse
  - test

regex_check:
  stage: analyse
  script:
    - ./regex_check.sh -v .

line_limit:
  stage: analyse
  script:
    - ./line_limit.sh -e '^\./test/line_limit/' -i -v .

test/line_limit:
  stage: test
  script:
    - cd test/line_limit
    - ./test.sh -v
